### ISSUE TITLE
UIMenu内存泄漏严重

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/DuiLib_Faw#12]
menu菜单多次使用,内存会一直泄漏

<img width="194" alt="menu内存泄漏" src="https://user-images.githubusercontent.com/29857592/178149311-30017f87-4a35-46d8-bef5-090e0ee8d539.png">

测试代码
[DuiLib_Faw-master.zip](https://github.com/fawdlstty/DuiLib_Faw/files/9079277/DuiLib_Faw-master.zip)

对策 参考[DuiLib_DuiEditor](https://github.com/xfcanyue/DuiLib_DuiEditor/blob/master/DuiLib/Control/UIMenu.cpp)
CMenuWnd::OnFinalMessage (HWND hWnd)  加上else部分的代码
```
	void CMenuWnd::OnFinalMessage (HWND hWnd) {
		RemoveObserver ();
		if (m_pOwner) {
                         ........
		}
		else
		{
				DestroyMenu();
				// 外部创建的也删除
				delete this;
		}
	}
```

效果如下,多次使用菜单内存平稳

<img width="228" alt="内存无泄漏" src="https://user-images.githubusercontent.com/29857592/178149541-1f821976-7f90-464d-912f-7b42b97f38e0.png">

**Comment by fawdlstty** [comment]
贴贴。貌似无效
