### ISSUE TITLE
RichEdit无法获取焦点

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/DuiLib_Faw#14]
问题参考
https://github.com/qdtroy/DuiLib_Ultimate/issues/112
https://github.com/qdtroy/DuiLib_Ultimate/issues/118

**Comment by wuwao1** [comment]
[BugDemo.zip 复现用例](https://github.com/fawdlstty/DuiLib_Faw/files/9337636/BugDemo.zip)

**Comment by wuwao1** [comment]
对策
AttachDialog 里面的 m_bFocusNeeded = true注释掉,或者改成m_bFocusNeeded = false;就正常了

**Comment by fawdlstty** [comment]
感谢，贴贴
