### ISSUE TITLE
资源文件加入字体无法取出(使用)

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/DuiLib_Faw#19]
XML添加类似`<Import fontfile="fontawesome-webfont.ttf"/>`
`void CPaintManagerUI::AddFontArray (faw::string_t pstrPath)`的`m_aFonts`保存了fontawesome-webfont.ttf,但是CPaintManagerUI没有提供函数可以获取到m_aFonts,供外部使用

**Comment by fawdlstty** [comment]
贴贴

**Comment by fawdlstty** [comment]
看了一下，理论上加载后，就可以直接通过Font标签指定字体了，持有句柄只是为了防止字体被卸载

**Comment by wuwao1** [comment]
字体安装到系统是可以正常识别的,但是从系统卸载后,使用`<Import fontfile="Alimama_ShuHeiTi_Bold.ttf"/>`,会无作用,变成默认字体
![屏幕截图 2022-11-05 200941](https://user-images.githubusercontent.com/29857592/200119585-ea9b2b6a-d8bc-4c95-b4ab-a9647c7f4181.jpg)
![屏幕截图 2022-11-05 200839](https://user-images.githubusercontent.com/29857592/200119587-1c12b64f-b613-4fa3-b888-cfec4f79e314.jpg)

测试用例如下
[Alimama_ShuHeiTi_Bold.zip](https://github.com/fawdlstty/DuiLib_Faw/files/9943761/Alimama_ShuHeiTi_Bold.zip)
[DuiLib_Faw-master.zip](https://github.com/fawdlstty/DuiLib_Faw/files/9943764/DuiLib_Faw-master.zip)

**Comment by fawdlstty** [comment]
我没找到从字体里提取字体名称的API，你有找到的话提一个pr或者回复下咯

**Comment by wuwao1** [comment]
手动解析字体文件获取字体名称，或者使用Gdiplus::PrivateFontCollection先AddFontFile再GetFamilies获取字体名称

**Comment by fawdlstty** [comment]
感觉这俩方案都不太行的样子

**Comment by wuwao1** [comment]
记错了,不是AddFontFile,是AddMemoryFont,在`void CPaintManagerUI::AddFontArray(faw::string_t pstrPath) `里面试了下面这一段代码是可以获取到字体名称的

```
		if (!pData || dwSize == 0) return;

		// 添加字体
		Gdiplus::PrivateFontCollection pCollection;
		pCollection.AddMemoryFont(pData, dwSize);

		int count = pCollection.GetFamilyCount();
		if (count == 0) return;

		int found = 0;
		Gdiplus::FontFamily* pFontFamily = (Gdiplus::FontFamily*)malloc(count * sizeof(Gdiplus::FontFamily));
		pCollection.GetFamilies(count, pFontFamily, &found);
		if (found == 0) {
			free(pFontFamily);
			return;
		}
		// 获取字体名称
		TCHAR  fontFamilyName[MAX_PATH] = { 0 };
		pFontFamily->GetFamilyName(fontFamilyName);
		free(pFontFamily);
```

**Comment by wuwao1** [comment]
done，so close it.

**Comment by fawdlstty** [comment]
贴贴
