### ISSUE TITLE
最新代码编译错误

### ISSUE THREAD

**Issue by bstaint** [fawdlstty/DuiLib_Faw#2]
SetupHelper.hpp：
> e:\3rdparty\gui\duilib_faw\duilib\3rd\fawlib\SetupHelper.hpp(140): error C2664: “HRESULT IShellLinkW::SetPath(LPCWSTR)”: 无法将参数 1 从“const _Elem *”转换为“LPCWSTR”

改成:
```
                                       psl->SetPath (_dest_file.strw ().c_str ());
                                       psl->SetWorkingDirectory (_work_path.strw ().c_str ());
```

之后报错：
>DuiLib\Control\UIEdit.cpp(231): error C2668: “faw::String::String”: 对重载函数的调用不明确

改成
```
faw::String str (_T ('\0'), cchLen);
```
之后报了几个：
>error C2678: 二进制“==”: 没有找到接受“const faw::String”类型的左操作数的运算符(或没有可接受的转换)

重载下面几个函数可以正常编译了：
```
		bool operator== (const String &_o) { String _co (_o); return m_str == _co.m_str; }

		friend bool operator== (const String &_o, String &_o2) { String _co (_o); return _o2  == _co; }
		friend bool operator== (const String &_o, const wchar_t * _s) { return _o.m_str == _s; }
```

**Comment by fawdlstty** [comment]
感谢反馈，已修改

**Comment by fawdlstty** [comment]
忘了提交，，晚上修复
