### ISSUE TITLE
CMenuWnd允许发送的消息类型限定太死

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/DuiLib_Faw#20]
[Descripttion] 菜单只允许click和valuechanged消息传出,需要使用其他消息类型只能修改源码

```
	void CMenuWnd::Notify (TNotifyUI& msg) {
		if (CMenuWnd::GetGlobalContextMenuObserver ().GetManager ()) {
			if (msg.sType == _T ("click") || msg.sType == _T ("valuechanged")) {
				CMenuWnd::GetGlobalContextMenuObserver ().GetManager ()->SendNotify (msg, false);
			}
		}
	}
```
[Expect Result]
允许应用端注册需要使用的消息类型

**Comment by fawdlstty** [comment]
贴贴。菜单还需要啥消息类型？

**Comment by wuwao1** [comment]
CMenuElementUI的鼠标点击产生的消息类型itemclick,传不出来,使用者需要修改源码
XML文件类似如下
```
<Menu>
    <MenuElement name="SaveDamnu" text="菜单测试1"  icon="DuiMenu/save.png" font="4" height="30">
    </MenuElement>
    <MenuElement name="Menu_Test3" text="菜单测试2" checkitem="true" ischeck="true" />
</Menu>
```

**Comment by fawdlstty** [comment]
有没有现在方式实现不了的功能呢？我感觉消息这俩够用了，菜单似乎不需要自定义获取其他消息

**Comment by wuwao1** [comment]
可以自定义MenuWindow类,继承CMenuWnd重写void Notify (TNotifyUI& msg);
试了一下是没问题的,不用每次拉取最新的库都去改源码了 🤣

**Comment by fawdlstty** [comment]
我比较想知道你实际遇到的情况是啥，为啥会需要菜单里面接收其他消息，如果确实有必要那么库也可以放开

**Comment by wuwao1** [comment]
https://github.com/fawdlstty/DuiLib_Faw/issues/8 这一个测试用例 , itemclick消息就发不出来

**Comment by fawdlstty** [comment]
我是想知道，为啥依靠上面两个消息，实现不了你所需要的功能，必须得其他消息才行？毕竟这个不行那个行嘛

**Comment by wuwao1** [comment]
比如Slider 就有很多消息类型,菜单作为一个窗体,就过掉了大多数消息,只留下click/valuechanged

`<Slider parent="Progress" notifies="setfocus killfocus timer menu valuechanged movevaluechanged windowinit(root)">`

假设有一个托盘菜单有Slider, movevaluechanged 消息就无法使用了
<img width="148" alt="2022-11-05 (3)" src="https://user-images.githubusercontent.com/29857592/200113993-c8efc31f-80b5-4540-9f0f-ee04ff653a67.png">

**Comment by fawdlstty** [comment]
很棒的想法，已修改
