### ISSUE TITLE
圆角矩形锯齿严重

### ISSUE THREAD

**Issue by wuwao1** [fawdlstty/DuiLib_Faw#9]
如图GDI绘制圆角锯齿严重
<img width="375" alt="屏幕截图 2022-06-29 122722" src="https://user-images.githubusercontent.com/29857592/176351717-9e986f2f-d094-4eb4-9c80-f9caf0d8708b.png">
个人修改使用GDI+的话效果很好
<img width="374" alt="屏幕截图 2022-06-29 122532" src="https://user-images.githubusercontent.com/29857592/176351808-7916cd15-da18-48c7-be40-547e29ec3e04.png">

**Comment by fawdlstty** [comment]
贴贴

**Comment by fawdlstty** [comment]
看了下，好像得大改，，，并且圆角对话框的对话框边框依旧得保留锯齿。除非圆角对话框也搞成分层窗口然后几个角透明。你有啥建议嘛？

**Comment by wuwao1** [comment]
我有个小改的方法，不知道副作用，
下班后再提供参考

**Comment by fawdlstty** [comment]
加个好友嘛 :·)

**Comment by wuwao1** [comment]
在群里哟 Decon

**Comment by wuwao1** [comment]
对策已导入
